# Error_Exception



## 예외(Exception)

: 실행 도중 예상하지 못한 상황(exception)을 맞이하면 프로그램 실행 멈춤.



`1) ZeroDivisionError : 0으로 나눌 때 발생`

`2) NameError : 정의되지 않은 변수를 호출할 때 발생`

`3) TypeError : 자료형에 대한 타입 자체가 잘못 되었을 경우`

`4) ValueError : 존재하지 않는 값을 찾고자 할 때`

`5) KeyError : 딕셔너리에서 key가 없는 경우`

`6) ModuleNotFoundError : 모듈을 찾을 수 없는 경우`

`7) ImportError: 모듈을 찾았으나 가져오는 과정에서 실패하는 경우 (존재하지 않는 클래스/함수 호출)`

`8) Keyboardinterrujpt:  주피터 노트북에서는 정지 버튼이지만, 실제로 우리가 돌릴때는 ctrl+c를 통해 종류했을때 발생`



## 예외 처리 (Exception Handling)

#### 활용법

```python
try:
    <코드 블럭 1>
except (예외):
    <코드 블럭 2>
```

- `try` 아래의 코드블락(code block)이 실행된다.
- 예외가 발생되지 않으면, **`except`없이 실행이 종료 된다.**
- 예외가 발생하면, **남은 부분을 수행하지 않고**, `except`가 실행된다.



```python
try:
    num = input('값을 입력하시오 : ')
    print(int(num))
except ValueError:
    print('숫자 넣어주세요')
```



### 에러 메시지 처리 `as`

`as` 키워드를 활용하여 에러 메시지를 보여줄 수도 있습니다.

------

#### 활용법

```python
try:
    <코드 블럭 1>
except 예외 as err:
    <코드 블럭 2>
```

```python
try:
    languages = {'python': 'good'}
    languages['java']
    
except KeyError as err:
    print(f'{err}는 딕셔너리에 없는 키입니다.')
    
    
    => 'java'는 딕셔너리에 없는 키입니다.
```



## 복수의 예외 처리

하나 이상의 예외를 모두 처리할 수 있습니다.

괄호가 있는 튜플로 여러 개의 예외를 지정할 수 있습니다.

------

#### 활용법

```python
try:
    <코드 블럭 1>
except (예외1, 예외2):
    <코드 블럭 2>


try:
    <코드 블럭 1>
except 예외1:
    <코드 블럭 2>
except 예외2:
    <코드 블럭 3>
```

```python
try:
    num = input('100을 나눌 값 넣어:')
    print(100/int(num))
    
except (ValueError, ZeroDivisionError):
    print('숫자나 0제외하고 입력하세요')  
```

```python
try:
    num = input('100을 나눌 값 넣어:')
    print(100/int(num))
    
except ValueError:
    print('숫자 입력하세요')
    
except ZeroDivisionError:
    print('0 제외하고 입력하세요')
    
else:
    print('good')
```





### `else`

- 에러가 발생하지 않는 경우 실행 시킬 문장은 `else`를 활용한다.
- `else`는 `except` 코드 뒤에 와야 한다.
- `try` 코드 블럭이 예외를 일으키지 않았을 때, 실행되어야 하는 코드에 사용된다.







### `finally`

- 어떤 경우에든 반드시 실행해야하는 코드에는 `finally`를 활용한다.
- 즉, 모든 상황에 실행되어야만 하는 코드를 정의하는데 활용한다.
- 예외의 발생 여부과 관계없이 항상 실행된다.

------

#### 활용법

```python
try:
    languages = {'python': 'good'}
    languages['java']
    
except KeyError as err:
    print(f'{err}는 딕셔너리에 없는 키입니다.')
    
finally:
    print('참고')
```



### [연습] `raise`를 활용하여 예외 발생시키기

### **raise** **예외('에러메시지')**

> 양의 정수 두개를 받아 몫을 출력하는 함수 `def my_div(num1, num2)`를 작성하세요.

------

- num2 가 0 이여서 발생하는 오류인 경우

   

  에러메시지

  를 출력합니다.

  - *예) division by zero 오류가 발생하였습니다.*

- 인자가 string 이여서 발생하는 경우는

   

  ValueError와 함께 '숫자를 넣어주세요'를 출력

  합니다.

  - (실제로 이 경우에 발생하는 것은 `TypeError`입니다.)

- 정상적인 경우에는 결과를 return합니다.



```python
def my_div(num1, num2):
    
    try:
    	if num2 == 0:                                 
        	raise Exception('0은 나눌 수 없습니다.')
            
        result = num1 // num2
        return result
    
   
            
	except Exception as e:                             
    	print('division by zero오류 발생.', e)
        
```

```python
try:
    x = int(input('3의 배수를 입력하세요: '))
    if x % 3 != 0:                                 # x가 3의 배수가 아니면
        raise Exception('3의 배수가 아닙니다.')    # 예외를 발생시킴
    print(x)
except Exception as e:                             # 예외가 발생했을 때 실행됨
    print('예외가 발생했습니다.', e)
```



### `assert`

`assert` 문은 예외를 발생시키는 다른 방법입니다.

보통 **상태를 검증하는데 사용**되며 무조건 `AssertionError`가 발생합니다.

------

**활용법**

```python
assert Boolean expression, error message

assert type(1) == int, '문자열을 입력하였습니다.'
```

------

위의 검증식이 거짓일 경우를 발생합니다.

`raise`는 항상 예외를 발생시키고, 지정한 예외가 발생한다는 점에서 다릅니다.



``` python
x = int(input('3의 배수를 입력하세요: '))
assert x % 3 == 0, '3의 배수가 아닙니다.'    # 3의 배수가 아니면 예외 발생, 3의 배수이면 그냥 넘어감
print(x)




3의 배수를 입력하세요: 5 (입력)
Traceback (most recent call last):
  File "C:\project\assertion.py", line 2, in <module>
    assert x % 3 == 0, '3의 배수가 아닙니다.'
AssertionError: 3의 배수가 아닙니다.
3의 배수를 입력하세요: 5 (입력)
Traceback (most recent call last):
  File "C:\project\assertion.py", line 2, in <module>
    assert x % 3 == 0, '3의 배수가 아닙니다.'
AssertionError: 3의 배수가 아닙니다.
```

